增加23级转数科分享
Luv-Ray/SZTU-Information pull request #7
Opened 2024-06-18 06:54 UTC by Dev-Crix

2024-06-18 07:07 UTC, Luv-Ray requested changes
建议 23 年的还是合在一个文件里。
如果觉得层次结构比较乱，可以修改之前的内容，或者单纯加在后面，后面我另外整理也可以

2024-06-20 06:51 UTC, Dev-Crix commented
现在这样可以不

2024-06-20 07:00 UTC, Luv-Ray approved these changes

2024-06-20 07:02 UTC, Luv-Ray commented
最后请把 git commit 信息 squash 成一个，具体操作可以看[这里](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)

2024-09-25 08:25 UTC, closed without merging